pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'

- task: NodeTool@0
  inputs:
    versionSpec: '6.x'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      gem install gist
      (umask 0077 && echo $(MY_SECRET_TOKEN) > ~/.gist)
      gist -u b4e53b549f0deaa27a01ab9955bce674 resume.json

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: npx resume-cli export resume.html

- download: current
  artifact: resume
  patterns: '**/*.html'