pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'


- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      gem install gist
      (umask 0077 && echo $(MY_SECRET_TOKEN) > ~/.gist)
      gist -u b4e53b549f0deaa27a01ab9955bce674 resume.json

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      sudo apt-get install tree

      sudo npm install npm@latest --global --allow-root
      sudo npm install --global resume-cli --unsafe-perm=true --allow-root
      sudo npm install jsonresume-theme-kwan --unsafe-perm=true --allow-root

      npm install jsonresume-theme-kwan
      resume export --theme kwan resume.html

      ls
      tree